2022-08-07T09:42:22.475Z	debug	1.3.0@a2d6c4b	Initializing API credentials	{"file": "/chainlink/apicredentials"}
2022-08-07T09:42:22.483Z	info	1.3.0@a2d6c4b.RunNode	Starting Chainlink Node 1.3.0 at commit a2d6c4b47d62ac792a215b3a8d3acfe3ae9a2966	{"Version": "1.3.0", "SHA": "a2d6c4b47d62ac792a215b3a8d3acfe3ae9a2966"}
2022-08-07T09:42:22.488Z	error	1.3.0@a2d6c4b	Cannot boot Chainlink: opening db: failed to open db: failed to connect to `host=chainlink-lukso-pg_chainlink-1 user=postgres database=chainlink-lukso`: dial error (dial tcp 172.18.0.2:5432: connect: connection refused)	{"err": "Cannot boot Chainlink: opening db: failed to open db: failed to connect to `host=chainlink-lukso-pg_chainlink-1 user=postgres database=chainlink-lukso`: dial error (dial tcp 172.18.0.2:5432: connect: connection refused)", "errVerbose": "opening db: failed to open db: failed to connect to `host=chainlink-lukso-pg_chainlink-1 user=postgres database=chainlink-lukso`: dial error (dial tcp 172.18.0.2:5432: connect: connection refused)\nCannot boot Chainlink\ngithub.com/smartcontractkit/chainlink/core/cmd.(*Client).RunNode\n\t/chainlink/core/cmd/local_client.go:53\ngithub.com/urfave/cli.HandleAction\n\t/go/pkg/mod/github.com/urfave/cli@v1.22.5/app.go:524\ngithub.com/urfave/cli.Command.Run\n\t/go/pkg/mod/github.com/urfave/cli@v1.22.5/command.go:173\ngithub.com/urfave/cli.(*App).RunAsSubcommand\n\t/go/pkg/mod/github.com/urfave/cli@v1.22.5/app.go:405\ngithub.com/urfave/cli.Command.startApp\n\t/go/pkg/mod/github.com/urfave/cli@v1.22.5/command.go:372\ngithub.com/urfave/cli.Command.Run\n\t/go/pkg/mod/github.com/urfave/cli@v1.22.5/command.go:102\ngithub.com/urfave/cli.(*App).Run\n\t/go/pkg/mod/github.com/urfave/cli@v1.22.5/app.go:277\nmain.Run\n\t/chainlink/core/main.go:25\nmain.main.func1\n\t/chainlink/core/main.go:18\ngithub.com/smartcontractkit/chainlink/core/recovery.ReportPanics\n\t/chainlink/core/recovery/recover.go:17\nmain.main\n\t/chainlink/core/main.go:17\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:255\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1581", "sentryEventID": null}
2022-08-07T09:43:01.670Z	debug	1.3.0@a2d6c4b	Initializing API credentials	{"file": "/chainlink/apicredentials"}
2022-08-07T09:43:01.676Z	info	1.3.0@a2d6c4b.RunNode	Starting Chainlink Node 1.3.0 at commit a2d6c4b47d62ac792a215b3a8d3acfe3ae9a2966	{"Version": "1.3.0", "SHA": "a2d6c4b47d62ac792a215b3a8d3acfe3ae9a2966"}
2022-08-07T09:43:01.679Z	error	1.3.0@a2d6c4b	Cannot boot Chainlink: opening db: failed to open db: failed to connect to `host=chainlink-lukso-pg_chainlink-1 user=postgres database=chainlink-lukso`: dial error (dial tcp 172.18.0.2:5432: connect: connection refused)	{"err": "Cannot boot Chainlink: opening db: failed to open db: failed to connect to `host=chainlink-lukso-pg_chainlink-1 user=postgres database=chainlink-lukso`: dial error (dial tcp 172.18.0.2:5432: connect: connection refused)", "errVerbose": "opening db: failed to open db: failed to connect to `host=chainlink-lukso-pg_chainlink-1 user=postgres database=chainlink-lukso`: dial error (dial tcp 172.18.0.2:5432: connect: connection refused)\nCannot boot Chainlink\ngithub.com/smartcontractkit/chainlink/core/cmd.(*Client).RunNode\n\t/chainlink/core/cmd/local_client.go:53\ngithub.com/urfave/cli.HandleAction\n\t/go/pkg/mod/github.com/urfave/cli@v1.22.5/app.go:524\ngithub.com/urfave/cli.Command.Run\n\t/go/pkg/mod/github.com/urfave/cli@v1.22.5/command.go:173\ngithub.com/urfave/cli.(*App).RunAsSubcommand\n\t/go/pkg/mod/github.com/urfave/cli@v1.22.5/app.go:405\ngithub.com/urfave/cli.Command.startApp\n\t/go/pkg/mod/github.com/urfave/cli@v1.22.5/command.go:372\ngithub.com/urfave/cli.Command.Run\n\t/go/pkg/mod/github.com/urfave/cli@v1.22.5/command.go:102\ngithub.com/urfave/cli.(*App).Run\n\t/go/pkg/mod/github.com/urfave/cli@v1.22.5/app.go:277\nmain.Run\n\t/chainlink/core/main.go:25\nmain.main.func1\n\t/chainlink/core/main.go:18\ngithub.com/smartcontractkit/chainlink/core/recovery.ReportPanics\n\t/chainlink/core/recovery/recover.go:17\nmain.main\n\t/chainlink/core/main.go:17\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:255\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1581", "sentryEventID": null}
2022-08-07T09:43:18.943Z	debug	1.3.0@a2d6c4b	Initializing API credentials	{"file": "/chainlink/apicredentials"}
2022-08-07T09:43:18.947Z	info	1.3.0@a2d6c4b.RunNode	Starting Chainlink Node 1.3.0 at commit a2d6c4b47d62ac792a215b3a8d3acfe3ae9a2966	{"Version": "1.3.0", "SHA": "a2d6c4b47d62ac792a215b3a8d3acfe3ae9a2966"}
2022-08-07T09:43:18.949Z	error	1.3.0@a2d6c4b	Cannot boot Chainlink: opening db: failed to open db: failed to connect to `host=chainlink-lukso-pg_chainlink-1 user=postgres database=chainlink-lukso`: dial error (dial tcp 172.18.0.2:5432: connect: connection refused)	{"err": "Cannot boot Chainlink: opening db: failed to open db: failed to connect to `host=chainlink-lukso-pg_chainlink-1 user=postgres database=chainlink-lukso`: dial error (dial tcp 172.18.0.2:5432: connect: connection refused)", "errVerbose": "opening db: failed to open db: failed to connect to `host=chainlink-lukso-pg_chainlink-1 user=postgres database=chainlink-lukso`: dial error (dial tcp 172.18.0.2:5432: connect: connection refused)\nCannot boot Chainlink\ngithub.com/smartcontractkit/chainlink/core/cmd.(*Client).RunNode\n\t/chainlink/core/cmd/local_client.go:53\ngithub.com/urfave/cli.HandleAction\n\t/go/pkg/mod/github.com/urfave/cli@v1.22.5/app.go:524\ngithub.com/urfave/cli.Command.Run\n\t/go/pkg/mod/github.com/urfave/cli@v1.22.5/command.go:173\ngithub.com/urfave/cli.(*App).RunAsSubcommand\n\t/go/pkg/mod/github.com/urfave/cli@v1.22.5/app.go:405\ngithub.com/urfave/cli.Command.startApp\n\t/go/pkg/mod/github.com/urfave/cli@v1.22.5/command.go:372\ngithub.com/urfave/cli.Command.Run\n\t/go/pkg/mod/github.com/urfave/cli@v1.22.5/command.go:102\ngithub.com/urfave/cli.(*App).Run\n\t/go/pkg/mod/github.com/urfave/cli@v1.22.5/app.go:277\nmain.Run\n\t/chainlink/core/main.go:25\nmain.main.func1\n\t/chainlink/core/main.go:18\ngithub.com/smartcontractkit/chainlink/core/recovery.ReportPanics\n\t/chainlink/core/recovery/recover.go:17\nmain.main\n\t/chainlink/core/main.go:17\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:255\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1581", "sentryEventID": null}
2022-08-07T09:44:34.399Z	debug	1.3.0@a2d6c4b	Initializing API credentials	{"file": "/chainlink/apicredentials"}
2022-08-07T09:44:34.404Z	info	1.3.0@a2d6c4b.RunNode	Starting Chainlink Node 1.3.0 at commit a2d6c4b47d62ac792a215b3a8d3acfe3ae9a2966	{"Version": "1.3.0", "SHA": "a2d6c4b47d62ac792a215b3a8d3acfe3ae9a2966"}
2022-08-07T09:44:34.407Z	error	1.3.0@a2d6c4b	Cannot boot Chainlink: opening db: failed to open db: failed to connect to `host=chainlink-lukso-pg_chainlink-1 user=postgres database=chainlink-lukso`: dial error (dial tcp 172.18.0.2:5432: connect: connection refused)	{"err": "Cannot boot Chainlink: opening db: failed to open db: failed to connect to `host=chainlink-lukso-pg_chainlink-1 user=postgres database=chainlink-lukso`: dial error (dial tcp 172.18.0.2:5432: connect: connection refused)", "errVerbose": "opening db: failed to open db: failed to connect to `host=chainlink-lukso-pg_chainlink-1 user=postgres database=chainlink-lukso`: dial error (dial tcp 172.18.0.2:5432: connect: connection refused)\nCannot boot Chainlink\ngithub.com/smartcontractkit/chainlink/core/cmd.(*Client).RunNode\n\t/chainlink/core/cmd/local_client.go:53\ngithub.com/urfave/cli.HandleAction\n\t/go/pkg/mod/github.com/urfave/cli@v1.22.5/app.go:524\ngithub.com/urfave/cli.Command.Run\n\t/go/pkg/mod/github.com/urfave/cli@v1.22.5/command.go:173\ngithub.com/urfave/cli.(*App).RunAsSubcommand\n\t/go/pkg/mod/github.com/urfave/cli@v1.22.5/app.go:405\ngithub.com/urfave/cli.Command.startApp\n\t/go/pkg/mod/github.com/urfave/cli@v1.22.5/command.go:372\ngithub.com/urfave/cli.Command.Run\n\t/go/pkg/mod/github.com/urfave/cli@v1.22.5/command.go:102\ngithub.com/urfave/cli.(*App).Run\n\t/go/pkg/mod/github.com/urfave/cli@v1.22.5/app.go:277\nmain.Run\n\t/chainlink/core/main.go:25\nmain.main.func1\n\t/chainlink/core/main.go:18\ngithub.com/smartcontractkit/chainlink/core/recovery.ReportPanics\n\t/chainlink/core/recovery/recover.go:17\nmain.main\n\t/chainlink/core/main.go:17\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:255\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1581", "sentryEventID": null}
2022-08-07T09:56:51.570Z	debug	1.3.0@a2d6c4b	Initializing API credentials	{"file": "/chainlink/apicredentials"}
2022-08-07T09:56:51.573Z	info	1.3.0@a2d6c4b.RunNode	Starting Chainlink Node 1.3.0 at commit a2d6c4b47d62ac792a215b3a8d3acfe3ae9a2966	{"Version": "1.3.0", "SHA": "a2d6c4b47d62ac792a215b3a8d3acfe3ae9a2966"}
2022-08-07T09:56:51.577Z	error	1.3.0@a2d6c4b	Cannot boot Chainlink: opening db: failed to open db: failed to connect to `host=chainlink-lukso-pg_chainlink-1 user=postgres database=chainlink-lukso`: dial error (dial tcp 172.18.0.2:5432: connect: connection refused)	{"err": "Cannot boot Chainlink: opening db: failed to open db: failed to connect to `host=chainlink-lukso-pg_chainlink-1 user=postgres database=chainlink-lukso`: dial error (dial tcp 172.18.0.2:5432: connect: connection refused)", "errVerbose": "opening db: failed to open db: failed to connect to `host=chainlink-lukso-pg_chainlink-1 user=postgres database=chainlink-lukso`: dial error (dial tcp 172.18.0.2:5432: connect: connection refused)\nCannot boot Chainlink\ngithub.com/smartcontractkit/chainlink/core/cmd.(*Client).RunNode\n\t/chainlink/core/cmd/local_client.go:53\ngithub.com/urfave/cli.HandleAction\n\t/go/pkg/mod/github.com/urfave/cli@v1.22.5/app.go:524\ngithub.com/urfave/cli.Command.Run\n\t/go/pkg/mod/github.com/urfave/cli@v1.22.5/command.go:173\ngithub.com/urfave/cli.(*App).RunAsSubcommand\n\t/go/pkg/mod/github.com/urfave/cli@v1.22.5/app.go:405\ngithub.com/urfave/cli.Command.startApp\n\t/go/pkg/mod/github.com/urfave/cli@v1.22.5/command.go:372\ngithub.com/urfave/cli.Command.Run\n\t/go/pkg/mod/github.com/urfave/cli@v1.22.5/command.go:102\ngithub.com/urfave/cli.(*App).Run\n\t/go/pkg/mod/github.com/urfave/cli@v1.22.5/app.go:277\nmain.Run\n\t/chainlink/core/main.go:25\nmain.main.func1\n\t/chainlink/core/main.go:18\ngithub.com/smartcontractkit/chainlink/core/recovery.ReportPanics\n\t/chainlink/core/recovery/recover.go:17\nmain.main\n\t/chainlink/core/main.go:17\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:255\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1581", "sentryEventID": null}
2022-08-07T09:57:07.958Z	debug	1.3.0@a2d6c4b	Initializing API credentials	{"file": "/chainlink/apicredentials"}
2022-08-07T09:57:07.960Z	info	1.3.0@a2d6c4b.RunNode	Starting Chainlink Node 1.3.0 at commit a2d6c4b47d62ac792a215b3a8d3acfe3ae9a2966	{"Version": "1.3.0", "SHA": "a2d6c4b47d62ac792a215b3a8d3acfe3ae9a2966"}
2022-08-07T09:57:07.962Z	error	1.3.0@a2d6c4b	Cannot boot Chainlink: opening db: failed to open db: failed to connect to `host=chainlink-lukso-pg_chainlink-1 user=postgres database=chainlink-lukso`: dial error (dial tcp 172.18.0.2:5432: connect: connection refused)	{"err": "Cannot boot Chainlink: opening db: failed to open db: failed to connect to `host=chainlink-lukso-pg_chainlink-1 user=postgres database=chainlink-lukso`: dial error (dial tcp 172.18.0.2:5432: connect: connection refused)", "errVerbose": "opening db: failed to open db: failed to connect to `host=chainlink-lukso-pg_chainlink-1 user=postgres database=chainlink-lukso`: dial error (dial tcp 172.18.0.2:5432: connect: connection refused)\nCannot boot Chainlink\ngithub.com/smartcontractkit/chainlink/core/cmd.(*Client).RunNode\n\t/chainlink/core/cmd/local_client.go:53\ngithub.com/urfave/cli.HandleAction\n\t/go/pkg/mod/github.com/urfave/cli@v1.22.5/app.go:524\ngithub.com/urfave/cli.Command.Run\n\t/go/pkg/mod/github.com/urfave/cli@v1.22.5/command.go:173\ngithub.com/urfave/cli.(*App).RunAsSubcommand\n\t/go/pkg/mod/github.com/urfave/cli@v1.22.5/app.go:405\ngithub.com/urfave/cli.Command.startApp\n\t/go/pkg/mod/github.com/urfave/cli@v1.22.5/command.go:372\ngithub.com/urfave/cli.Command.Run\n\t/go/pkg/mod/github.com/urfave/cli@v1.22.5/command.go:102\ngithub.com/urfave/cli.(*App).Run\n\t/go/pkg/mod/github.com/urfave/cli@v1.22.5/app.go:277\nmain.Run\n\t/chainlink/core/main.go:25\nmain.main.func1\n\t/chainlink/core/main.go:18\ngithub.com/smartcontractkit/chainlink/core/recovery.ReportPanics\n\t/chainlink/core/recovery/recover.go:17\nmain.main\n\t/chainlink/core/main.go:17\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:255\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1581", "sentryEventID": null}
2022-08-07T10:11:53.924Z	debug	1.3.0@a2d6c4b	Initializing API credentials	{"file": "/chainlink/apicredentials"}
2022-08-07T10:11:53.931Z	info	1.3.0@a2d6c4b.RunNode	Starting Chainlink Node 1.3.0 at commit a2d6c4b47d62ac792a215b3a8d3acfe3ae9a2966	{"Version": "1.3.0", "SHA": "a2d6c4b47d62ac792a215b3a8d3acfe3ae9a2966"}
2022-08-07T10:11:57.866Z	error	1.3.0@a2d6c4b	Cannot boot Chainlink: opening db: failed to open db: failed to connect to `host=chainlink-lukso-pg_chainlink-1 user=postgres database=chainlink-lukso`: hostname resolving error (lookup chainlink-lukso-pg_chainlink-1 on 127.0.0.11:53: no such host)	{"err": "Cannot boot Chainlink: opening db: failed to open db: failed to connect to `host=chainlink-lukso-pg_chainlink-1 user=postgres database=chainlink-lukso`: hostname resolving error (lookup chainlink-lukso-pg_chainlink-1 on 127.0.0.11:53: no such host)", "errVerbose": "opening db: failed to open db: failed to connect to `host=chainlink-lukso-pg_chainlink-1 user=postgres database=chainlink-lukso`: hostname resolving error (lookup chainlink-lukso-pg_chainlink-1 on 127.0.0.11:53: no such host)\nCannot boot Chainlink\ngithub.com/smartcontractkit/chainlink/core/cmd.(*Client).RunNode\n\t/chainlink/core/cmd/local_client.go:53\ngithub.com/urfave/cli.HandleAction\n\t/go/pkg/mod/github.com/urfave/cli@v1.22.5/app.go:524\ngithub.com/urfave/cli.Command.Run\n\t/go/pkg/mod/github.com/urfave/cli@v1.22.5/command.go:173\ngithub.com/urfave/cli.(*App).RunAsSubcommand\n\t/go/pkg/mod/github.com/urfave/cli@v1.22.5/app.go:405\ngithub.com/urfave/cli.Command.startApp\n\t/go/pkg/mod/github.com/urfave/cli@v1.22.5/command.go:372\ngithub.com/urfave/cli.Command.Run\n\t/go/pkg/mod/github.com/urfave/cli@v1.22.5/command.go:102\ngithub.com/urfave/cli.(*App).Run\n\t/go/pkg/mod/github.com/urfave/cli@v1.22.5/app.go:277\nmain.Run\n\t/chainlink/core/main.go:25\nmain.main.func1\n\t/chainlink/core/main.go:18\ngithub.com/smartcontractkit/chainlink/core/recovery.ReportPanics\n\t/chainlink/core/recovery/recover.go:17\nmain.main\n\t/chainlink/core/main.go:17\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:255\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1581", "sentryEventID": null}
2022-08-07T10:12:05.584Z	debug	1.3.0@a2d6c4b	Initializing API credentials	{"file": "/chainlink/apicredentials"}
2022-08-07T10:12:05.588Z	info	1.3.0@a2d6c4b.RunNode	Starting Chainlink Node 1.3.0 at commit a2d6c4b47d62ac792a215b3a8d3acfe3ae9a2966	{"Version": "1.3.0", "SHA": "a2d6c4b47d62ac792a215b3a8d3acfe3ae9a2966"}
2022-08-07T10:12:09.507Z	error	1.3.0@a2d6c4b	Cannot boot Chainlink: opening db: failed to open db: failed to connect to `host=chainlink-lukso-pg_chainlink-1 user=postgres database=chainlink-lukso`: hostname resolving error (lookup chainlink-lukso-pg_chainlink-1 on 127.0.0.11:53: no such host)	{"err": "Cannot boot Chainlink: opening db: failed to open db: failed to connect to `host=chainlink-lukso-pg_chainlink-1 user=postgres database=chainlink-lukso`: hostname resolving error (lookup chainlink-lukso-pg_chainlink-1 on 127.0.0.11:53: no such host)", "errVerbose": "opening db: failed to open db: failed to connect to `host=chainlink-lukso-pg_chainlink-1 user=postgres database=chainlink-lukso`: hostname resolving error (lookup chainlink-lukso-pg_chainlink-1 on 127.0.0.11:53: no such host)\nCannot boot Chainlink\ngithub.com/smartcontractkit/chainlink/core/cmd.(*Client).RunNode\n\t/chainlink/core/cmd/local_client.go:53\ngithub.com/urfave/cli.HandleAction\n\t/go/pkg/mod/github.com/urfave/cli@v1.22.5/app.go:524\ngithub.com/urfave/cli.Command.Run\n\t/go/pkg/mod/github.com/urfave/cli@v1.22.5/command.go:173\ngithub.com/urfave/cli.(*App).RunAsSubcommand\n\t/go/pkg/mod/github.com/urfave/cli@v1.22.5/app.go:405\ngithub.com/urfave/cli.Command.startApp\n\t/go/pkg/mod/github.com/urfave/cli@v1.22.5/command.go:372\ngithub.com/urfave/cli.Command.Run\n\t/go/pkg/mod/github.com/urfave/cli@v1.22.5/command.go:102\ngithub.com/urfave/cli.(*App).Run\n\t/go/pkg/mod/github.com/urfave/cli@v1.22.5/app.go:277\nmain.Run\n\t/chainlink/core/main.go:25\nmain.main.func1\n\t/chainlink/core/main.go:18\ngithub.com/smartcontractkit/chainlink/core/recovery.ReportPanics\n\t/chainlink/core/recovery/recover.go:17\nmain.main\n\t/chainlink/core/main.go:17\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:255\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1581", "sentryEventID": null}
2022-08-07T10:36:43.127Z	debug	1.3.0@a2d6c4b	Initializing API credentials	{"file": "/chainlink/apicredentials"}
2022-08-07T10:36:43.132Z	info	1.3.0@a2d6c4b.RunNode	Starting Chainlink Node 1.3.0 at commit a2d6c4b47d62ac792a215b3a8d3acfe3ae9a2966	{"Version": "1.3.0", "SHA": "a2d6c4b47d62ac792a215b3a8d3acfe3ae9a2966"}
2022-08-07T10:36:47.072Z	error	1.3.0@a2d6c4b	Cannot boot Chainlink: opening db: failed to open db: failed to connect to `host=chainlink-lukso-pg_chainlink-1 user=postgres database=chainlink-lukso`: hostname resolving error (lookup chainlink-lukso-pg_chainlink-1 on 127.0.0.11:53: no such host)	{"err": "Cannot boot Chainlink: opening db: failed to open db: failed to connect to `host=chainlink-lukso-pg_chainlink-1 user=postgres database=chainlink-lukso`: hostname resolving error (lookup chainlink-lukso-pg_chainlink-1 on 127.0.0.11:53: no such host)", "errVerbose": "opening db: failed to open db: failed to connect to `host=chainlink-lukso-pg_chainlink-1 user=postgres database=chainlink-lukso`: hostname resolving error (lookup chainlink-lukso-pg_chainlink-1 on 127.0.0.11:53: no such host)\nCannot boot Chainlink\ngithub.com/smartcontractkit/chainlink/core/cmd.(*Client).RunNode\n\t/chainlink/core/cmd/local_client.go:53\ngithub.com/urfave/cli.HandleAction\n\t/go/pkg/mod/github.com/urfave/cli@v1.22.5/app.go:524\ngithub.com/urfave/cli.Command.Run\n\t/go/pkg/mod/github.com/urfave/cli@v1.22.5/command.go:173\ngithub.com/urfave/cli.(*App).RunAsSubcommand\n\t/go/pkg/mod/github.com/urfave/cli@v1.22.5/app.go:405\ngithub.com/urfave/cli.Command.startApp\n\t/go/pkg/mod/github.com/urfave/cli@v1.22.5/command.go:372\ngithub.com/urfave/cli.Command.Run\n\t/go/pkg/mod/github.com/urfave/cli@v1.22.5/command.go:102\ngithub.com/urfave/cli.(*App).Run\n\t/go/pkg/mod/github.com/urfave/cli@v1.22.5/app.go:277\nmain.Run\n\t/chainlink/core/main.go:25\nmain.main.func1\n\t/chainlink/core/main.go:18\ngithub.com/smartcontractkit/chainlink/core/recovery.ReportPanics\n\t/chainlink/core/recovery/recover.go:17\nmain.main\n\t/chainlink/core/main.go:17\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:255\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1581", "sentryEventID": null}
2022-08-07T10:46:15.798Z	debug	1.3.0@a2d6c4b	Initializing API credentials	{"file": "/chainlink/apicredentials"}
2022-08-07T10:46:15.802Z	info	1.3.0@a2d6c4b.RunNode	Starting Chainlink Node 1.3.0 at commit a2d6c4b47d62ac792a215b3a8d3acfe3ae9a2966	{"Version": "1.3.0", "SHA": "a2d6c4b47d62ac792a215b3a8d3acfe3ae9a2966"}
2022-08-07T10:46:19.706Z	error	1.3.0@a2d6c4b	Cannot boot Chainlink: opening db: failed to open db: failed to connect to `host=chainlink-lukso-pg_chainlink-1 user=postgres database=chainlink-lukso`: hostname resolving error (lookup chainlink-lukso-pg_chainlink-1 on 127.0.0.11:53: no such host)	{"err": "Cannot boot Chainlink: opening db: failed to open db: failed to connect to `host=chainlink-lukso-pg_chainlink-1 user=postgres database=chainlink-lukso`: hostname resolving error (lookup chainlink-lukso-pg_chainlink-1 on 127.0.0.11:53: no such host)", "errVerbose": "opening db: failed to open db: failed to connect to `host=chainlink-lukso-pg_chainlink-1 user=postgres database=chainlink-lukso`: hostname resolving error (lookup chainlink-lukso-pg_chainlink-1 on 127.0.0.11:53: no such host)\nCannot boot Chainlink\ngithub.com/smartcontractkit/chainlink/core/cmd.(*Client).RunNode\n\t/chainlink/core/cmd/local_client.go:53\ngithub.com/urfave/cli.HandleAction\n\t/go/pkg/mod/github.com/urfave/cli@v1.22.5/app.go:524\ngithub.com/urfave/cli.Command.Run\n\t/go/pkg/mod/github.com/urfave/cli@v1.22.5/command.go:173\ngithub.com/urfave/cli.(*App).RunAsSubcommand\n\t/go/pkg/mod/github.com/urfave/cli@v1.22.5/app.go:405\ngithub.com/urfave/cli.Command.startApp\n\t/go/pkg/mod/github.com/urfave/cli@v1.22.5/command.go:372\ngithub.com/urfave/cli.Command.Run\n\t/go/pkg/mod/github.com/urfave/cli@v1.22.5/command.go:102\ngithub.com/urfave/cli.(*App).Run\n\t/go/pkg/mod/github.com/urfave/cli@v1.22.5/app.go:277\nmain.Run\n\t/chainlink/core/main.go:25\nmain.main.func1\n\t/chainlink/core/main.go:18\ngithub.com/smartcontractkit/chainlink/core/recovery.ReportPanics\n\t/chainlink/core/recovery/recover.go:17\nmain.main\n\t/chainlink/core/main.go:17\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:255\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1581", "sentryEventID": null}
2022-08-07T10:57:54.453Z	debug	1.3.0@a2d6c4b	Initializing API credentials	{"file": "/chainlink/apicredentials"}
2022-08-07T10:57:54.456Z	info	1.3.0@a2d6c4b.RunNode	Starting Chainlink Node 1.3.0 at commit a2d6c4b47d62ac792a215b3a8d3acfe3ae9a2966	{"Version": "1.3.0", "SHA": "a2d6c4b47d62ac792a215b3a8d3acfe3ae9a2966"}
2022-08-07T10:57:58.355Z	error	1.3.0@a2d6c4b	Cannot boot Chainlink: opening db: failed to open db: failed to connect to `host=chainlink-lukso-pg_chainlink-1 user=postgres database=chainlink-lukso`: hostname resolving error (lookup chainlink-lukso-pg_chainlink-1 on 127.0.0.11:53: no such host)	{"err": "Cannot boot Chainlink: opening db: failed to open db: failed to connect to `host=chainlink-lukso-pg_chainlink-1 user=postgres database=chainlink-lukso`: hostname resolving error (lookup chainlink-lukso-pg_chainlink-1 on 127.0.0.11:53: no such host)", "errVerbose": "opening db: failed to open db: failed to connect to `host=chainlink-lukso-pg_chainlink-1 user=postgres database=chainlink-lukso`: hostname resolving error (lookup chainlink-lukso-pg_chainlink-1 on 127.0.0.11:53: no such host)\nCannot boot Chainlink\ngithub.com/smartcontractkit/chainlink/core/cmd.(*Client).RunNode\n\t/chainlink/core/cmd/local_client.go:53\ngithub.com/urfave/cli.HandleAction\n\t/go/pkg/mod/github.com/urfave/cli@v1.22.5/app.go:524\ngithub.com/urfave/cli.Command.Run\n\t/go/pkg/mod/github.com/urfave/cli@v1.22.5/command.go:173\ngithub.com/urfave/cli.(*App).RunAsSubcommand\n\t/go/pkg/mod/github.com/urfave/cli@v1.22.5/app.go:405\ngithub.com/urfave/cli.Command.startApp\n\t/go/pkg/mod/github.com/urfave/cli@v1.22.5/command.go:372\ngithub.com/urfave/cli.Command.Run\n\t/go/pkg/mod/github.com/urfave/cli@v1.22.5/command.go:102\ngithub.com/urfave/cli.(*App).Run\n\t/go/pkg/mod/github.com/urfave/cli@v1.22.5/app.go:277\nmain.Run\n\t/chainlink/core/main.go:25\nmain.main.func1\n\t/chainlink/core/main.go:18\ngithub.com/smartcontractkit/chainlink/core/recovery.ReportPanics\n\t/chainlink/core/recovery/recover.go:17\nmain.main\n\t/chainlink/core/main.go:17\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:255\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1581", "sentryEventID": null}
